// Datos de noticias (09 March 2026) - 50 noticias
const newsData = [
    { title: "How AI is turning the Iran conflict into theater", summary: "This story originally appeared in The Algorithm, our weekly newsletter on AI. To get stories like this in your inbox first,Â sign up here. â€œAnyone wanna host a get together in SF and pull this up on...", link: "https://www.technologyreview.com/2026/03/09/1134063/how-ai-is-turning-the-iran-conflict-into-theater/", source: "MIT Tech Review" },
    { title: "Is the Pentagon allowed to surveil Americans with AI?", summary: "The ongoing public feud between the Department of Defense and the AI company Anthropic has raised a deep and still unanswered question: Does the law actually allow the US government to conduct mass su...", link: "https://www.technologyreview.com/2026/03/06/1134012/is-the-pentagon-allowed-to-surveil-americans-with-ai/", source: "MIT Tech Review" },
    { title: "Online harassment is entering its AI era", summary: "Scott Shambaugh didnâ€™t think twice when he denied an AI agentâ€™s request to contribute to matplotlib, a software library that he helps manage. Like many open-source projects, matplotlib has been ov...", link: "https://www.technologyreview.com/2026/03/05/1133962/online-harassment-is-entering-its-ai-era/", source: "MIT Tech Review" },
    { title: "Bridging the operational AI gap", summary: "The transformational potential of AI is already well established. Enterprise use cases are building momentum and organizations are transitioning from pilot projects to AI in production. Companies are ...", link: "https://www.technologyreview.com/2026/03/04/1133642/bridging-the-operational-ai-gap/", source: "MIT Tech Review" },
    { title: "OpenAIâ€™s “compromise” with the Pentagon is what Anthropic feared", summary: "On February 28, OpenAI announced it had reached a deal that will allow the US military to use its technologies in classified settings. CEO Sam Altman said the negotiations, which the company began pur...", link: "https://www.technologyreview.com/2026/03/02/1133850/openais-compromise-with-the-pentagon-is-what-anthropic-feared/", source: "MIT Tech Review" },
    { title: "I checked out one of the biggest anti-AI protests yet", summary: "Pull the plug! Pull the plug! Stop the slop! Stop the slop! For a few hours this Saturday, February 28, I watched as a couple of hundred anti-AI protesters marched through Londonâ€™s Kingâ€™s Cross te...", link: "https://www.technologyreview.com/2026/03/02/1133814/i-checked-out-londons-biggest-ever-anti-ai-protest/", source: "MIT Tech Review" },
    { title: "AI is rewiring how the worldâ€™s best Go players think", summary: "Burrowed in the alleys of Hongik-dong, a hushed residential neighborhood in eastern Seoul, is a faded stone-tiled building stamped â€œKorea Baduk Association,â€ the governing body for professional Go...", link: "https://www.technologyreview.com/2026/02/27/1133624/ai-is-rewiring-how-the-worlds-best-go-players-think/", source: "MIT Tech Review" },
    { title: "Finding value with AI and Industry 5.0 transformation", summary: "For years, Industry 4.0 transformation has centered on the convergence of intelligent technologies like AI, cloud, the internet of things, robotics, and digital twins. Industry 5.0 marks a pivotal shi...", link: "https://www.technologyreview.com/2026/02/26/1133707/finding-value-with-ai-and-industry-5-0-transformation/", source: "MIT Tech Review" },
    { title: "The human work behind humanoid robots is being hidden", summary: "This story originally appeared in The Algorithm, our weekly newsletter on AI. To get stories like this in your inbox first,Â sign up here. In January, Nvidiaâ€™s Jensen Huang, the head of the worldâ€™...", link: "https://www.technologyreview.com/2026/02/23/1133508/the-human-work-behind-humanoid-robots-is-being-hidden/", source: "MIT Tech Review" },
    { title: "Microsoft has a new plan to prove whatâ€™s real and whatâ€™s AI online", summary: "AI-enabled deception now permeates our online lives. There are the high-profile cases you may easily spot, like when White House officials recently shared a manipulated image of a protester in Minneso...", link: "https://www.technologyreview.com/2026/02/19/1133360/microsoft-has-a-new-plan-to-prove-whats-real-and-whats-ai-online/", source: "MIT Tech Review" },
    { title: "The usability imperative for securing digital asset devices", summary: "When Tony Fadell started working on the iPod, usability often trumped security. The result was an iterative process. Every time someone would find a security weakness or a way to hack the device, the ...", link: "https://www.technologyreview.com/2026/03/09/1132352/the-usability-imperative-for-securing-digital-asset-devices/", source: "MIT Tech" },
    { title: "The Download: murky AI surveillance laws, and the White House cracks down on defiant labs", summary: "This is today&#8217;s edition of The Download, our weekday newsletter that provides a daily dose of what&#8217;s going on in the world of technology. Is the Pentagon allowed to surveil Americans with ...", link: "https://www.technologyreview.com/2026/03/09/1134050/the-download-ai-surveillance-laws-white-house-cracks-down-defiant-labs/", source: "MIT Tech" },
    { title: "The Download: 10 things that matter in AI, plus Anthropic’s plan to sue the Pentagon", summary: "This is today&#8217;s edition of The Download, our weekday newsletter that provides a daily dose of what&#8217;s going on in the world of technology. Coming soon: our 10 Things That Matter in AI Right...", link: "https://www.technologyreview.com/2026/03/06/1133989/the-download-10-things-that-matter-in-ai-anthropics-plan-sue-pentagon/", source: "MIT Tech" },
    { title: "The Download: an AI agent’s hit piece, and preventing lightning", summary: "This is today&#8217;s edition of The Download, our weekday newsletter that provides a daily dose of what&#8217;s going on in the world of technology. Online harassment is entering its AI era Scott Sha...", link: "https://www.technologyreview.com/2026/03/05/1133968/the-download-ai-agent-hit-piece-preventing-lightning/", source: "MIT Tech" },
    { title: "How much wildfire prevention is too much?", summary: "The race to prevent the worst wildfires has been an increasingly high-tech one. Companies are proposing AI fire detection systems and drones that can stamp out early blazes. And now, one Canadian star...", link: "https://www.technologyreview.com/2026/03/05/1133960/wildfire-prevention-limits/", source: "MIT Tech" },
    { title: "The Download: Earth’s rumblings, and AI for strikes on Iran", summary: "This is today&#8217;s edition of The Download, our weekday newsletter that provides a daily dose of what&#8217;s going on in the world of technology. Listen to Earthâ€™s rumbling, secret soundtrack Th...", link: "https://www.technologyreview.com/2026/03/04/1133942/the-download-earths-rumblings-and-ai-for-strikes-on-iran/", source: "MIT Tech" },
    { title: "Your Espresso Machine Doesnâ€™t Have to Be Fancy to Make Good Coffee", summary: "A former barista explains why your espresso machine doesn't have to be fancy to make quality coffee.", link: "https://www.wired.com/story/casabrews-5700-espresso-machine-java-base/", source: "Wired" },
    { title: "Our Favorite Wireless Headphones Are $60 Off", summary: "The Sony WH-1000XM6 get a noticeable markdown for a limited time.", link: "https://www.wired.com/story/sony-wh-1000xm6-deal-326/", source: "Wired" },
    { title: "Anthropic Sues Department of Defense Over Supply-Chain-Risk Designation", summary: "The Claude chatbot developer says the Trump administration overstepped by escalating a contract dispute into a federal ban on the companyâ€™s technology.", link: "https://www.wired.com/story/anthropic-sues-department-of-defense-over-supply-chain-risk-designation/", source: "Wired" },
    { title: "Best Base Layers (2026): Merino Wool, Synthetic, and More", summary: "Whether youâ€™re layering up for winter cold or looking for an ultralight summer system, Iâ€™ve tested and found the best base layers for all your outdoor adventures.", link: "https://www.wired.com/gallery/best-base-layers/", source: "Wired" },
    { title: "Feeld Was a Dating App for the Freaks. Now Some People Call It â€˜Normie Hellâ€™", summary: "The app that catered to unconventional kinks is gaining steam among daters with vanilla preferencesâ€”and some arenâ€™t happy about it.", link: "https://www.wired.com/story/feeld-was-a-dating-app-for-the-freaks-now-some-people-call-it-normie-hell/", source: "Wired" },
    { title: "Apple iPhone 17e Review: MagSafe Makes a Difference", summary: "A bump in storage and the addition of MagSafe make Appleâ€™s cheapest iPhone a better value proposition than its predecessor.", link: "https://www.wired.com/review/apple-iphone-17e/", source: "Wired" },
    { title: "Best Sonos Speakers (2026): Soundbars, Headphones, Dolby Atmos, and More", summary: "From smart speakert so soundbars, Sonos makes the best streaming speakers you can buy. These are my personal favorites.", link: "https://www.wired.com/gallery/best-sonos-speakers-buying-guide/", source: "Wired" },
    { title: "Hatchâ€™s Sale Has the Restore 3, Rest, and Rest+ All Discounted", summary: "Hatchâ€™s sunrise alarm clock is popular for a reason, and itâ€™s on sale this week. An older-model sound machine for babies is on sale too.", link: "https://www.wired.com/story/hatch-sleep-week-sale-2026/", source: "Wired" },
    { title: "Donâ€™t Expect Big Surprises in the Governmentâ€™s Alien Files", summary: "Donald Trump has ordered the release of files related to aliens, UAP, and UFOs. If previous disclosures are any indication, get ready for a letdown.", link: "https://www.wired.com/story/dont-expect-big-surprises-in-the-governments-alien-files/", source: "Wired" },
    { title: "Are Smart Beds Worth It? A Certified Sleep Science Coach Weighs In (2026)", summary: "These tech-packed beds can adjust firmness, track your sleep, and regulate temperature automatically. Based on my testing, here's what's worth the investment.", link: "https://www.wired.com/gallery/best-smart-beds/", source: "Wired" },
    { title: "Why RFKâ€™s CDC Is Endorsing â€˜Shared Decisionmakingâ€™ for Vaccines", summary: "The MAHA movement is recasting the termâ€”developed in the 1980s to help protect patients against paternalistic medicineâ€”in service of its own agenda.", link: "https://www.wired.com/story/why-rfks-cdc-is-endorsing-shared-decision-making-for-vaccines/", source: "Wired" },
    { title: "Can AI Kill the Venture Capitalist?", summary: "VCs are betting that artificial intelligence will disrupt nearly every industry in the world. Are they prepared for it to disrupt their own?", link: "https://www.wired.com/story/ai-kill-venture-capital/", source: "Wired" },
    { title: "H&R Block Coupon: $50 Off Assisted Tax Prep", summary: "When you visit your local H&R Block store or get help from a tax pro online, you can save up to $50 when you use one of our (unique) codes.", link: "https://www.wired.com/story/hr-block-coupon/", source: "Wired" },
    { title: "How to Run Ethernet Cables to Your Router and Keep Them Tidy", summary: "Boosting internet speeds around your home is easy with Ethernet cables, and these tips will help you keep things neat.", link: "https://www.wired.com/story/how-to-run-ethernet-cables-around-your-home/", source: "Wired" },
    { title: "Force Your MacBook to Only Charge up to 80 Percent (and Why You Should)", summary: "Laptop batteries lag in performance as they age. But you can slow down their deterioration by tweaking your Macâ€™s charging settings.", link: "https://www.wired.com/story/only-charge-your-macbook-to-80-percent/", source: "Wired" },
    { title: "Fender Mix Headphones Review: Modular Over-Ears", summary: "Say goodbye to disposable headphones with Fenderâ€™s customizable and replaceable parts.", link: "https://www.wired.com/review/fender-audio-mix/", source: "Wired" },
    { title: "A Certified Sleep Coach Shares the Sleep Week Deals Sheâ€™s Adding to Cart (2026)", summary: "From mattresses to sateen sheets, these exclusive deals on my personal picks can help you upgrade your sleep for less.", link: "https://www.wired.com/story/sleep-week-deals-2026/", source: "Wired" },
    { title: "The Moka Pot Is the Best Way to Brew Coffee (2026)", summary: "Bialettiâ€™s timeless design doesnâ€™t just look good. It makes an incredible cup thatâ€™s perfect to keep you awake through the time change.", link: "https://www.wired.com/story/moka-pot-best-way-to-brew-coffee/", source: "Wired" },
    { title: "Best Sunrise Alarm Clock (2026): Lumie, Hatch, WiiM", summary: "Iâ€™ve never been a morning person. This bedside gadget is the only thing thatâ€™s ever changed that.", link: "https://www.wired.com/story/should-you-get-a-sunrise-alarm-clock/", source: "Wired" },
    { title: "Left-Handed People Are More Competitive, Says Science", summary: "A recent study suggests that left-handed people have an advantage in competitive contexts, while righties tend to cooperate better.", link: "https://www.wired.com/story/left-handed-people-are-more-competitive-says-science/", source: "Wired" },
    { title: "Why the Ratio Four Series Two Is What I Use to Test New Coffees", summary: "A new generation of home machines has made good old drip coffee a place for connoisseurs. For more than a year, the Four is the source of my morning cup.", link: "https://www.wired.com/story/ratio-four-drip-coffee-java-base/", source: "Wired" },
    { title: "The WIRED Guide to Wires: How to Manage the Mess of Cables Around Your Desk", summary: "You need to sort out that ratâ€™s nest of cables under your desk. These cable management tips and products can help you do it.", link: "https://www.wired.com/story/fix-the-dangling-wires-behind-your-desk/", source: "Wired" },
    { title: "The Best MIDI Controllers for Synths, Guitars, and More (2026)", summary: "Want to digitally control your favorite instruments? These tools will help.", link: "https://www.wired.com/gallery/best-midi-controllers/", source: "Wired" },
    { title: "Best Mid Layer for Hiking, Backpacking, and Travel (2026)", summary: "Should you get a high-tech jacket like a grid fleece, or stick with tried and true merino wool? We found the warmest, lightest mid layers for your next adventure.", link: "https://www.wired.com/gallery/best-mid-layers/", source: "Wired" },
    { title: "CBP Used Online Ad Data to Track Phone Locations", summary: "Plus: Proton helped the FBI identify a protester, the Leakbase cybercrime forum was busted in an international operation, and more.", link: "https://www.wired.com/story/cbp-used-online-ad-data-to-track-phone-locations/", source: "Wired" },
    { title: "How Each Gulf Country Is Intercepting Iranian Missiles and Drones", summary: "As missiles and drones cross the regionâ€™s skies, the Gulfâ€™s layered air-defense networksâ€”from THAAD to Patriot batteriesâ€”are being tested in real time.", link: "https://www.wired.com/story/how-each-gulf-country-is-intercepting-iranian-missiles-and-drones/", source: "Wired" },
    { title: "How to Avoid Getting Locked Out of Your Google Account", summary: "Make a recovery plan now to avoid losing access to your account in the future.", link: "https://www.wired.com/story/how-to-avoid-getting-locked-out-of-your-google-account/", source: "Wired" },
    { title: "This Jammer Wants to Block Always-Listening AI Wearables. It Probably Wonâ€™t Work", summary: "Deveillanceâ€™s Spectre I, developed by a recent Harvard grad, wants to give people control over the always-on wearables surrounding their lives. The problem? Physics.", link: "https://www.wired.com/story/deveillance-spectre-i/", source: "Wired" },
    { title: "Marley Spoon Meal Kit Review 2026: Less Martha, More Moroccan", summary: "Marley Spoon has stripped Martha Stewart from its website and seems to be cooking a little differently. Hereâ€™s a review.", link: "https://www.wired.com/review/marley-spoon-meal-kit-2026/", source: "Wired" },
    { title: "72 'Buy It for Life' Products: Cast-Iron, Tools, Speakers, Chairs, and More", summary: "From cast-iron pans to mechanical watches, weâ€™ve rounded up products that are made to last for decades.", link: "https://www.wired.com/story/buy-it-for-life/", source: "Wired" },
    { title: "The Best Google Pixel Phones of 2026, Tested and Reviewed", summary: "Hereâ€™s a guide to all the modelsâ€”plus Pixel case recommendations and smart software tricks to try.", link: "https://www.wired.com/story/best-google-pixel-phone/", source: "Wired" },
    { title: "The Future of Iranâ€™s Internet Is More Uncertain Than Ever", summary: "Iranâ€™s internet shutdown has reduced connectivity by 99 percent, with air strikes likely causing additional outages, and few workarounds remaining.", link: "https://www.wired.com/story/the-future-of-irans-internet-is-more-uncertain-than-ever/", source: "Wired" },
    { title: "These Beats Headphones We Like Are $150 Off", summary: "Save a chunk of change on the Beats Studio Pro over-ear headphones.", link: "https://www.wired.com/story/beats-studio-pro-deal-326/", source: "Wired" },
    { title: "When AI Companies Go to War, Safety Gets Left Behind", summary: "We were promised AI regulation and a race to the top. Now, weâ€™re arguing about killer robots.", link: "https://www.wired.com/story/when-ai-companies-go-to-war-safety-gets-left-behind/", source: "Wired" },
];
function formatDate(date) {
    const options = { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'Europe/Madrid' };
    return date.toLocaleDateString('es-ES', options);
}
function createNewsCard(news, index) {
    const card = document.createElement('article');
    card.className = 'news-card';
    card.style.animationDelay = (index * 0.1) + 's';
    card.innerHTML = '<a href="' + news.link + '" target="_blank" class="news-title">' + news.title + '</a><p class="news-summary">' + news.summary + '</p><a href="' + news.link + '" target="_blank" class="news-link">Leer mas</a>';
    return card;
}
function loadNews() {
    var container = document.getElementById('news-container');
    container.innerHTML = '';
    for (var i = 0; i < newsData.length; i++) {
        container.appendChild(createNewsCard(newsData[i], i));
    }
}
function updateLastUpdateTime() {
    document.getElementById('update-time').textContent = formatDate(new Date());
}
function init() {
    console.log('BladeRunner Tech News: ' + newsData.length + ' noticias');
    loadNews();
    updateLastUpdateTime();
}
document.addEventListener('DOMContentLoaded', init);
