// Datos de noticias (09 March 2026) - 50 noticias
const newsData = [
    { title: "OpenAI to acquire Promptfoo", summary: "OpenAI is acquiring Promptfoo, an AI security platform that helps enterprises identify and remediate vulnerabilities in AI systems during development.", link: "https://openai.com/index/openai-to-acquire-promptfoo", source: "OpenAI" },
    { title: "How Descript enables multilingual video dubbing at scale", summary: "Descript uses OpenAI models to scale multilingual video dubbing, optimizing translations for both meaning and timing so dubbed speech sounds natural across languages.", link: "https://openai.com/index/descript", source: "OpenAI" },
    { title: "Codex Security: now in research preview", summary: "Codex Security is an AI application security agent that analyzes project context to detect, validate, and patch complex vulnerabilities with higher confidence and less noise.", link: "https://openai.com/index/codex-security-now-in-research-preview", source: "OpenAI" },
    { title: "How Balyasny Asset Management built an AI research engine for investing", summary: "See how Balyasny built an AI research system with GPT-5.4, rigorous model evaluation, and agent workflows to transform investment analysis at scale.", link: "https://openai.com/index/balyasny-asset-management", source: "OpenAI" },
    { title: "GPT-5.4 Thinking System Card", summary: "Sin descripcion", link: "https://openai.com/index/gpt-5-4-thinking-system-card", source: "OpenAI" },
    { title: "Introducing GPT-5.4", summary: "Introducing GPT-5.4, OpenAIâ€™s most most capable and efficient frontier model for professional work, with state-of-the-art coding, computer use, tool search, and 1M-token context.", link: "https://openai.com/index/introducing-gpt-5-4", source: "OpenAI" },
    { title: "Reasoning models struggle to control their chains of thought, and thatâ€™s good", summary: "OpenAI introduces CoT-Control and finds reasoning models struggle to control their chains of thought, reinforcing monitorability as an AI safety safeguard.", link: "https://openai.com/index/reasoning-models-chain-of-thought-controllability", source: "OpenAI" },
    { title: "Ensuring AI use in education leads to opportunity", summary: "OpenAI shares new tools, certifications, and measurement resources to help schools and universities close AI capability gaps and expand opportunity.", link: "https://openai.com/index/ai-education-opportunity", source: "OpenAI" },
    { title: "The five AI value models driving business reinvention", summary: "Five AI value models show how leaders can sequence AI from workforce fluency to process reinvention and build durable business advantage.", link: "https://openai.com/index/the-five-ai-value-models-driving-business-reinvention", source: "OpenAI" },
    { title: "Introducing the Adoption news channel", summary: "Practical insights and frameworks to turn AI progress into business advantage", link: "https://openai.com/index/introducing-the-adoption-news-channel", source: "OpenAI" },
    { title: "Introducing ChatGPT for Excel and new financial data integrations", summary: "OpenAI introduces ChatGPT for Excel and new financial app integrations, powered by GPT-5.4 to accelerate modeling, research, and analysis in regulated environments.", link: "https://openai.com/index/chatgpt-for-excel", source: "OpenAI" },
    { title: "Extending single-minus amplitudes to gravitons", summary: "A new preprint extends single-minus amplitudes to gravitons, with GPT-5.2 Pro helping derive and verify nonzero graviton tree amplitudes in quantum gravity.", link: "https://openai.com/index/extending-single-minus-amplitudes-to-gravitons", source: "OpenAI" },
    { title: "Understanding AI and learning outcomes", summary: "OpenAI introduces the Learning Outcomes Measurement Suite to assess AIâ€™s impact on student learning across diverse educational environments over time.", link: "https://openai.com/index/understanding-ai-and-learning-outcomes", source: "OpenAI" },
    { title: "How Axios uses AI to help deliver high-impact local journalism", summary: "Axios COO Allison Murphy explains how the company uses AI to support local reporters, streamline newsroom workflows, and deliver high-impact local journalism at scale.", link: "https://openai.com/index/axios-allison-murphy", source: "OpenAI" },
    { title: "GPT-5.3 Instant: Smoother, more useful everyday conversations", summary: "Sin descripcion", link: "https://openai.com/index/gpt-5-3-instant", source: "OpenAI" },
    { title: "GPT-5.3 Instant System Card", summary: "Sin descripcion", link: "https://openai.com/index/gpt-5-3-instant-system-card", source: "OpenAI" },
    { title: "Our agreement with the Department of War", summary: "Details on OpenAIâ€™s contract with the Department of War, outlining safety red lines, legal protections, and how AI systems will be deployed in classified environments.", link: "https://openai.com/index/our-agreement-with-the-department-of-war", source: "OpenAI" },
    { title: "Scaling AI for everyone", summary: "Today weâ€™re announcing $110B in new investment at a $730B pre money valuation. This includes $30B from SoftBank, $30B from NVIDIA, and $50B from Amazon.", link: "https://openai.com/index/scaling-ai-for-everyone", source: "OpenAI" },
    { title: "Joint Statement from OpenAI and Microsoft", summary: "Microsoft and OpenAI continue to work closely across research, engineering, and product development, building on years of deep collaboration and shared success.", link: "https://openai.com/index/continuing-microsoft-partnership", source: "OpenAI" },
    { title: "OpenAI and Amazon announce strategic partnership", summary: "OpenAI and Amazon announce a strategic partnership bringing OpenAIâ€™s Frontier platform to AWS, expanding AI infrastructure, custom models, and enterprise AI agents.", link: "https://openai.com/index/amazon-partnership", source: "OpenAI" },
    { title: "Introducing the Stateful Runtime Environment for Agents in Amazon Bedrock", summary: "Stateful Runtime for Agents in Amazon Bedrock brings persistent orchestration, memory, and secure execution to multi-step AI workflows powered by OpenAI.", link: "https://openai.com/index/introducing-the-stateful-runtime-environment-for-agents-in-amazon-bedrock", source: "OpenAI" },
    { title: "An update on our mental health-related work", summary: "OpenAI shares updates on its mental health safety work, including parental controls, trusted contacts, improved distress detection, and recent litigation developments.", link: "https://openai.com/index/update-on-mental-health-related-work", source: "OpenAI" },
    { title: "Pacific Northwest National Laboratory and OpenAI partner to accelerate federal permitting", summary: "OpenAI and Pacific Northwest National Laboratory introduce DraftNEPABench, a new benchmark evaluating how AI coding agents can accelerate federal permittingâ€”showing potential to reduce NEPA drafting...", link: "https://openai.com/index/pacific-northwest-national-laboratory", source: "OpenAI" },
    { title: "OpenAI Codex and Figma launch seamless code-to-design experience", summary: "OpenAI and Figma launch a new Codex integration that connects code and design, enabling teams to move between implementation and the Figma canvas to iterate and ship faster.", link: "https://openai.com/index/figma-partnership", source: "OpenAI" },
    { title: "Disrupting malicious uses of AI | February 2026", summary: "Our latest threat report examines how malicious actors combine AI models with websites and social platformsâ€”and what it means for detection and defense.", link: "https://openai.com/index/disrupting-malicious-ai-uses", source: "OpenAI" },
    { title: "Arvind KC appointed Chief People Officer", summary: "OpenAI appoints Arvind KC as Chief People Officer to help scale the company, strengthen its culture, and lead how work evolves in the age of AI.", link: "https://openai.com/index/arvind-kc-chief-people-officer", source: "OpenAI" },
    { title: "Why we no longer evaluate SWE-bench Verified", summary: "SWE-bench Verified is increasingly contaminated and mismeasures frontier coding progress. Our analysis shows flawed tests and training leakage. We recommend SWE-bench Pro.", link: "https://openai.com/index/why-we-no-longer-evaluate-swe-bench-verified", source: "OpenAI" },
    { title: "OpenAI announces Frontier Alliance Partners", summary: "OpenAI announces Frontier Alliance Partners to help enterprises move from AI pilots to production with secure, scalable agent deployments.", link: "https://openai.com/index/frontier-alliance-partners", source: "OpenAI" },
    { title: "Our First Proof submissions", summary: "We share our AI modelâ€™s proof attempts for the First Proof math challenge, testing research-grade reasoning on expert-level problems.", link: "https://openai.com/index/first-proof-submissions", source: "OpenAI" },
    { title: "Advancing independent research on AI alignment", summary: "OpenAI commits $7.5M to The Alignment Project to fund independent AI alignment research, strengthening global efforts to address AGI safety and security risks.", link: "https://openai.com/index/advancing-independent-research-ai-alignment", source: "OpenAI" },
    { title: "Introducing OpenAI for India", summary: "OpenAI for India expands AI access across the countryâ€”building local infrastructure, powering enterprises, and advancing workforce skills.", link: "https://openai.com/index/openai-for-india", source: "OpenAI" },
    { title: "Introducing EVMbench", summary: "OpenAI and Paradigm introduce EVMbench, a benchmark evaluating AI agentsâ€™ ability to detect, patch, and exploit high-severity smart contract vulnerabilities.", link: "https://openai.com/index/introducing-evmbench", source: "OpenAI" },
    { title: "GPT-5.2 derives a new result in theoretical physics", summary: "A new preprint shows GPT-5.2 proposing a new formula for a gluon amplitude, later formally proved and verified by OpenAI and academic collaborators.", link: "https://openai.com/index/new-result-theoretical-physics", source: "OpenAI" },
    { title: "Introducing Lockdown Mode and Elevated Risk labels in ChatGPT", summary: "Introducing Lockdown Mode and Elevated Risk labels in ChatGPT to help organizations defend against prompt injection and AI-driven data exfiltration.", link: "https://openai.com/index/introducing-lockdown-mode-and-elevated-risk-labels-in-chatgpt", source: "OpenAI" },
    { title: "Beyond rate limits: scaling access to Codex and Sora", summary: "How OpenAI built a real-time access system combining rate limits, usage tracking, and credits to power continuous access to Sora and Codex.", link: "https://openai.com/index/beyond-rate-limits", source: "OpenAI" },
    { title: "Scaling social science research", summary: "GABRIEL is a new open-source toolkit from OpenAI that uses GPT to turn qualitative text and images into quantitative data, helping social scientists analyze research at scale.", link: "https://openai.com/index/scaling-social-science-research", source: "OpenAI" },
    { title: "Introducing GPT-5.3-Codex-Spark", summary: "Introducing GPT-5.3-Codex-Sparkâ€”our first real-time coding model. 15x faster generation, 128k context, now in research preview for ChatGPT Pro users.", link: "https://openai.com/index/introducing-gpt-5-3-codex-spark", source: "OpenAI" },
    { title: "Harness engineering: leveraging Codex in an agent-first world", summary: "By Ryan Lopopolo, Member of the Technical Staff", link: "https://openai.com/index/harness-engineering", source: "OpenAI" },
    { title: "Testing ads in ChatGPT", summary: "OpenAI begins testing ads in ChatGPT to support free access, with clear labeling, answer independence, strong privacy protections, and user control.", link: "https://openai.com/index/testing-ads-in-chatgpt", source: "OpenAI" },
    { title: "Bringing ChatGPT to GenAI.mil", summary: "OpenAI for Government announces the deployment of a custom ChatGPT on GenAI.mil, bringing secure, safety-forward AI to U.S. defense teams.", link: "https://openai.com/index/bringing-chatgpt-to-genaimil", source: "OpenAI" },
    { title: "Making AI work for everyone, everywhere: our approach to localization", summary: "OpenAI shares its approach to AI localization, showing how globally shared frontier models can be adapted to local languages, laws, and cultures without compromising safety.", link: "https://openai.com/index/our-approach-to-localization", source: "OpenAI" },
    { title: "GPT-5 lowers the cost of cell-free protein synthesis", summary: "An autonomous lab combining OpenAIâ€™s GPT-5 with Ginkgo Bioworksâ€™ cloud automation cut cell-free protein synthesis costs by 40% through closed-loop experimentation.", link: "https://openai.com/index/gpt-5-lowers-protein-synthesis-cost", source: "OpenAI" },
    { title: "Introducing Trusted Access for Cyber", summary: "OpenAI introduces Trusted Access for Cyber, a trust-based framework that expands access to frontier cyber capabilities while strengthening safeguards against misuse.", link: "https://openai.com/index/trusted-access-for-cyber", source: "OpenAI" },
    { title: "Introducing OpenAI Frontier", summary: "OpenAI Frontier is an enterprise platform for building, deploying, and managing AI agents with shared context, onboarding, permissions, and governance.", link: "https://openai.com/index/introducing-openai-frontier", source: "OpenAI" },
    { title: "Introducing GPT-5.3-Codex", summary: "GPT-5.3-Codex is a Codex-native agent that pairs frontier coding performance with general reasoning to support long-horizon, real-world technical work.", link: "https://openai.com/index/introducing-gpt-5-3-codex", source: "OpenAI" },
    { title: "GPT-5.3-Codex System Card", summary: "GPTâ€‘5.3-Codex is the most capable agentic coding model to date, combining the frontier coding performance of GPTâ€‘5.2-Codex with the reasoning and professional knowledge capabilities of GPTâ€‘5.2.", link: "https://openai.com/index/gpt-5-3-codex-system-card", source: "OpenAI" },
    { title: "Navigating health questions with ChatGPT", summary: "A family shares how ChatGPT helped them prepare for critical cancer treatment decisions for their son alongside expert guidance from his doctors.", link: "https://openai.com/index/navigating-health-questions", source: "OpenAI" },
    { title: "Unlocking the Codex harness: how we built the App Server", summary: "Learn how to embed the Codex agent using the Codex App Server, a bidirectional JSON-RPC API powering streaming progress, tool use, approvals, and diffs.", link: "https://openai.com/index/unlocking-the-codex-harness", source: "OpenAI" },
    { title: "VfL Wolfsburg turns ChatGPT into a club-wide capability", summary: "By focusing on people, not pilots, the Bundesliga club is scaling efficiency, creativity, and knowledgeâ€”without losing its football identity.", link: "https://openai.com/index/vfl-wolfsburg", source: "OpenAI" },
    { title: "The Sora feed philosophy", summary: "Discover the Sora feed philosophyâ€”built to spark creativity, foster connections, and keep experiences safe with personalized recommendations, parental controls, and strong guardrails.", link: "https://openai.com/index/sora-feed-philosophy", source: "OpenAI" },
];
function formatDate(date) {
    const options = { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'Europe/Madrid' };
    return date.toLocaleDateString('es-ES', options);
}
function createNewsCard(news, index) {
    const card = document.createElement('article');
    card.className = 'news-card';
    card.style.animationDelay = (index * 0.1) + 's';
    card.innerHTML = '<a href="' + news.link + '" target="_blank" class="news-title">' + news.title + '</a><p class="news-summary">' + news.summary + '</p><a href="' + news.link + '" target="_blank" class="news-link">Leer mas</a>';
    return card;
}
function loadNews() {
    var container = document.getElementById('news-container');
    container.innerHTML = '';
    for (var i = 0; i < newsData.length; i++) {
        container.appendChild(createNewsCard(newsData[i], i));
    }
}
function updateLastUpdateTime() {
    document.getElementById('update-time').textContent = formatDate(new Date());
}
function init() {
    console.log('BladeRunner Tech News: ' + newsData.length + ' noticias');
    loadNews();
    updateLastUpdateTime();
}
document.addEventListener('DOMContentLoaded', init);
